version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
