name: Build boring image
on:
  workflow_dispatch:
    inputs:
      goversion:
        description: 'Go version'
        required: true
        default: '1.17.9b7'
      tarsha256:
        description: 'SHA-256 for the downloaded Go distribution tar file'
        required: true
        default: '9469d1b4c10f59c921c4666c52baba5f6ca63b1cce0eca95e03b5713ef27577c'

jobs:
  build-image:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "${{ github.repository_owner }}/goboring"

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Image version
        id: image-version
        run: |
          echo Basic Metadata
          echo "event: ${{ github.event_name }}"
          echo "repository: ${{ github.repository }}"
          echo "context URL: ${{ github.repositoryUrl }}#${{ github.ref }}"
          echo "context URL: ${{ github.repositoryUrl }}/tree/${{ github.ref_name }}/docker/goboring"
          echo "git ref: ${{ github.ref }}"
          echo "goversion: ${{ github.event.inputs.goversion }}"
          imageVersion=${{ github.event.inputs.goversion }}-$(date +%Y.%d.%m-%H%m)
          echo "::set-output name=imageVersion::${imageVersion}"
          echo "${REGISTRY}/${IMAGE_NAME}:${imageVersion}"

      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            ${{ github.event.inputs.goversion }}
            ${{ github.event.inputs.goversion }}-{{date 'YYYY.MM.DD-hhmm'}}

      - name: Log to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref_name }}/docker/goboring/Dockerfile
          build-args: |
            goVersion=${{ github.event.inputs.goversion }}
            tarSha256=${{ github.event.inputs.tarsha256 }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
