name: Build boring image
on:
  workflow_dispatch:
    inputs:
      goversion:
        description: 'Go version'
        required: true
        default: '1.17.8b7'

jobs:
  Docker-Image:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "${{ github.repository_owner }}/goboring"

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Image version
        id: image-version
        run: |
          echo Basic Metadata
          echo "event: ${{ github.event_name }}"
          echo "repository: ${{ github.repository }}"
          echo "git ref: ${{ github.ref }}"
          echo "goversion: ${{ github.event.inputs.goversion }}"
          echo "::set-output name=imageVersion::$(git log -1 --format=%ad-%h --date=format:'%Y.%d.%m-%H%m')"
          echo "${REGISTRY}/${IMAGE_NAME}:${{ steps.image-version.outputs.imageVersion }}"

      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            ${{ github.event.inputs.goversion }}
            ${{ steps.image-version.outputs.imageVersion }}

      - name: Log to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: docker/goboring
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
