name: GHA Test
on: [push]
jobs:
  GHA-Test:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "${{ github.repository_owner }}/golang"
      TS: "$(date +%Y.%m.%d-%H%M%S)"

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Basic metadata
        run: |
          echo "event: ${{ github.event_name }}"
          echo "os: ${{ runner.os }}"
          echo "branch: ${{ github.ref }}"
          echo "repository: ${{ github.repository }}"
          echo "workspace dir: ${{ github.workspace }}"
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "TS=${TS}"
          TS="$(date +%Y.%m.%d-%H%M%S)"
          echo "${REGISTRY}/${IMAGE_NAME}/golang:idle-${TS}"

          # docker build --build-arg imageVersion="${TS}" \
          #   --tag "${REGISTRY}/${IMAGE_NAME}/golang:idle-${TS}" \
          #   docker/golang-idle

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker/golang-idle
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

#      - uses: actions/setup-go@v2
#        with:
#          go-version: '^1.17' # The Go version to download (if necessary) and use.
#      - run: go version

      - run: echo "status of this job:${{ job.status }}"
