name: Go build
on:
  pull_request:
  push:
    branches: [ main, ci-test ]
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Basic metadata
        run: |
          echo "event: ${{ github.event_name }}"
          echo "os: ${{ runner.os }}"
          echo "branch: ${{ github.ref }}"
          echo "repository: ${{ github.repository }}"
          echo "workspace dir: ${{ github.workspace }}"
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - run: go version
      - name: Check out repository
        uses: actions/checkout@v3
      # TODO: build code
      - run: go build ./...
      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.2"
          install-go: false
      - run: echo "status of this job:${{ job.status }}"
