name: Go build
on:
  pull_request:
  push:
    branches: [ main, ci-test ]
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
          cache: true
      -
        name: Job's basic metadata
        run: |
          echo "event: ${{ github.event_name }}"
          echo "os: ${{ runner.os }}"
          echo "branch: ${{ github.ref }}"
          echo "repository: ${{ github.repository }}"
          echo "workspace dir: ${{ github.workspace }}"
          go version
      -
        run: go build ./...
      -
        run: "go test ./..."
      -
        run: "go vet ./..."
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.54
      -
        name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.2"
          install-go: false
      -
        run: echo "status of this job:${{ job.status }}"
