name: Go build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Basic metadata
        run: |
          echo "event: ${{ github.event_name }}"
          echo "os: ${{ runner.os }}"
          echo "branch: ${{ github.ref }}"
          echo "repository: ${{ github.repository }}"
          echo "workspace dir: ${{ github.workspace }}"
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - run: go version
      - name: Check out repository
        uses: actions/checkout@v3
      # TODO: build code
      - run: echo "status of this job:${{ job.status }}"
